conditioning:
  method: ps
  params:
    scale: 0.5

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_prob_range: !!python/tuple [0.3, 0.7]
    image_size: 128
  noise:
    name: gaussian
    sigma: 0.05

data:
  name: aoa_amp_building
  root: ./data/building_training
  map_size: [128, 128]
  grid_spacing: 1.0
  bs_grid_spacing: 2.0
  building_configs:
    - {x: 20, y: 20, width: 30, height: 15}
    - {x: 75, y: 56, width: 25, height: 19}
  use_existing_data: True
  normalize_data: True
  num_samples: 16
